Get 10% sample and remove column

In [2]:
from snowflake.snowpark import Session
from snowflake.ml.utils.connection_params import SnowflakeLoginOptions
session = Session.builder.configs(SnowflakeLoginOptions("test_conn")).create()

df = session.table("HOUSING").sample(frac=0.10).to_pandas()
df.shape
X = df.loc[:, df.columns != 'MEDIAN_HOUSE_VALUE']
X

,LONGITUDE,LATITUDE,HOUSING_MEDIAN_AGE,TOTAL_ROOMS,TOTAL_BEDROOMS,POPULATION,HOUSEHOLDS,MEDIAN_INCOME,OCEAN_PROXIMITY
0,-122.26,37.84,50.0,2239.0,455.0,990.0,419.0,1.9911,NEAR BAY
1,-122.28,37.85,41.0,535.0,123.0,317.0,119.0,2.4038,NEAR BAY
2,-122.26,37.83,52.0,1665.0,419.0,946.0,395.0,2.0978,NEAR BAY
3,-122.27,37.82,40.0,946.0,375.0,700.0,352.0,1.7750,NEAR BAY
4,-122.27,37.82,21.0,896.0,453.0,735.0,438.0,0.9218,NEAR BAY
...,...,...,...,...,...,...,...,...,...
2023,-121.58,39.12,26.0,2796.0,629.0,2017.0,632.0,1.8355,INLAND
2024,-121.53,39.06,20.0,561.0,109.0,308.0,114.0,3.3021,INLAND
2025,-121.48,39.05,40.0,198.0,41.0,151.0,48.0,4.5625,INLAND
2026,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
2027,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND