Get 10% sample from a table data

In [3]:
from snowflake.snowpark import Session
from snowflake.ml.utils.connection_params import SnowflakeLoginOptions

session = Session.builder.configs(SnowflakeLoginOptions("test_conn")).create()
df = session.table("HOUSING")
df.sample(frac=0.10).show()

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"LONGITUDE"  |"LATITUDE"  |"HOUSING_MEDIAN_AGE"  |"TOTAL_ROOMS"  |"TOTAL_BEDROOMS"  |"POPULATION"  |"HOUSEHOLDS"  |"MEDIAN_INCOME"  |"MEDIAN_HOUSE_VALUE"  |"OCEAN_PROXIMITY"  |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|-122.27      |37.85       |42.0                  |1639.0         |367.0             |929.0         |366.0         |1.7135           |159800.0              |NEAR BAY           |
|-122.28      |37.85       |49.0                  |1130.0         |244.0             |607.0         |239.0         |2.4597           |93800.0               |NEAR BAY           |
|-122.28      |37.84       |52.0                  |729.0          |160.0             |395.0         |155.0         |1.6875           |132000.0              |NEAR BAY           |
|-122.26      |37.83       |52.0                  |1665.0         |419.0             |946.0         |395.0         |2.0978           |155400.0              |NEAR BAY           |
|-122.27      |37.82       |40.0                  |946.0          |375.0             |700.0         |352.0         |1.7750           |112500.0              |NEAR BAY           |
|-122.27      |37.82       |52.0                  |1630.0         |456.0             |1162.0        |400.0         |1.2475           |104200.0              |NEAR BAY           |
|-122.25      |37.81       |52.0                  |1758.0         |460.0             |686.0         |422.0         |3.1691           |259400.0              |NEAR BAY           |
|-122.25      |37.83       |35.0                  |1613.0         |428.0             |675.0         |422.0         |3.4722           |243100.0              |NEAR BAY           |
|-122.20      |37.84       |35.0                  |2865.0         |460.0             |1072.0        |443.0         |7.4882           |319300.0              |NEAR BAY           |
|-122.22      |37.81       |52.0                  |1971.0         |335.0             |765.0         |308.0         |6.5217           |273700.0              |NEAR BAY           |
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [4]:
pdf = df.to_pandas().sample(frac=0.10)
pdf

,LONGITUDE,LATITUDE,HOUSING_MEDIAN_AGE,TOTAL_ROOMS,TOTAL_BEDROOMS,POPULATION,HOUSEHOLDS,MEDIAN_INCOME,MEDIAN_HOUSE_VALUE,OCEAN_PROXIMITY
20080,-120.43,38.02,15.0,1613.0,299.0,655.0,251.0,3.6875,186000.0,INLAND
7147,-118.14,34.03,44.0,2003.0,390.0,1291.0,392.0,4.0625,201100.0,<1H OCEAN
15653,-122.39,37.80,25.0,4561.0,1474.0,1525.0,1169.0,4.5581,500001.0,NEAR BAY
19194,-122.69,38.44,35.0,1356.0,241.0,620.0,216.0,3.5521,168300.0,<1H OCEAN
16395,-121.22,38.00,35.0,1841.0,300.0,783.0,285.0,2.8167,162100.0,INLAND
...,...,...,...,...,...,...,...,...,...,...
8076,-118.19,33.83,30.0,2246.0,552.0,1032.0,548.0,3.5871,347100.0,NEAR OCEAN
5651,-118.29,33.73,43.0,1854.0,519.0,1151.0,486.0,2.5759,225000.0,NEAR OCEAN
5911,-118.43,34.28,27.0,862.0,280.0,1243.0,267.0,2.3724,154200.0,<1H OCEAN
3712,-118.40,34.19,37.0,934.0,231.0,587.0,230.0,3.6250,181300.0,<1H OCEAN
1574,-122.03,37.83,24.0,5948.0,738.0,1997.0,710.0,9.8708,500001.0,NEAR BAY